name: backend template

on:
  push:

jobs:
  my-first-job:
    runs-on: windows-latest  # Windows environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run tests
        run: npm test
